# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MScEE Electrical Engineering Projects (EEPs) in Mixed-Technology System Design 
author: M. Meiners 
copyright: ""
logo: images/hsb-logo.png
exclude_patterns: ["LICENSE.md", "README.md"]
only_build_toc_files: true
# Short description about the book
description: >-
  Electrical Engineering Projects (EEP).

# execute:
#  execute_notebooks: cache

# HTML-specific settings
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: true
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  navbar_number_sections: true
  baseurl: "https://mimeiners.github.io/eeps/"

  comments:
    hypothesis: true
    utterances:
      repo: "mimeiners/eeps"
      dokieli: true
  extra_footer : |
    <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">
      <img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
      All content on this site (unless otherwise specified) is licensed under the 
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
    </div>


# LaTeX settings
bibtex_bibfiles:
  - _bibliography/references.bib
latex:
  latex_documents:
    targetname: eeps.tex

# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"
  
repository:
  url: https://github.com/mimeiners/eeps

# Advanced and power-user settings
sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    html_show_copyright: true
    html_extra_path: ['files']
    language: en
    bibtex_reference_style: author_year
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

    myst_enable_extensions: 
    - amsmath
    - dollarmath
    - colon_fence
    - deflist
    - html_image
    - linkify
    - replacements
    - substitution


    myst_substitutions:
      INSTRUCTOR: "Prof. Dr.-Ing. Mirco Meiners (he/his/him)"
      OFFICE: "E 508"
      PHONE: "N/A"
      COURSE_CODE: "Electrical Engineering Projects"
      CREDITS: "6"
      TITLE: "Electrical Engineering Projects in Mixed-Technolgy System Design"
      TERM: "Summer and Winter"
      MEETING_TIMES: "By Arrangement"
      ASSOCIATE_HEAD: "Tim Ziemann [tim.ziemann@hs-bremen.de](mailto:tim.ziemann@hs-bremen.de)"
