project:
  type: book
  output-dir: _book
  
lang: en

book:
  title: "MScEE Electrical Engineering Projects (EEP)"
  date: 2024-11-11
  author:
    - name: Mirco Meiners
      email: Mirco.Meiners@hs-bremen.de
      affiliation:
        - name: Hochschule Bremen - City University of Applied Sciences
          city: Bremen
          country: Germany
          url: www.hs-bremen.de

  reader-mode: true

  page-footer:
    left: |
      MScEE Electrical Engineering Project (EEP), M. Meiners.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
#  cover-image: images/hsb-logo.png
#  favicon: images/hsb-logo.png
  site-url: https://mimeiners.github.io/eeps/
  repo-url: https://github.com/mimeiners/eeps/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd

    - part: Projects
      chapters:
        - file: docs/mojo.qmd
        - file: docs/osic-tools.qmd
        - file: docs/references.qmd
          
bibliography: _bibliography/references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrbook # scrreptrt
#    lof: true
#    lot: true
    toc: true    
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: ieee
    #    keep-tex: true
    output-file: eeps
  epub:
    theme: flatly
    output-file: eeps
  docx: default

execute:
  freeze: auto

editor: visual
