project:
  type: book
  output-dir: _book
  
lang: en

book:
  title: "MScEE Electrical Engineering Projects (EEP) in Mixed-Tefhnology Systems"
  date: 2024-11-11
  author:
    - name: Mirco Meiners
      orcid: 0000-0002-9709-4191
      email: Mirco.Meiners@hs-bremen.de
      corresponding: true
      roles: "Lead author"
      affiliation:
        - name: Hochschule Bremen - City University of Applied Sciences (HSB)
          city: Bremen
          state: Germany
          url: https://www.hs-bremen.de/person/mimeiners/ 
    - name: Erik Müller
      email: emueller@stud.hs-bremen.de
      roles: "Supporting author"
    - name: Abishek Padiya
      email: apadiya@stud.hs-bremen.de
      roles: "Supporting author"
  date: last-modified
  license: "Apache-2.0 license"

  reader-mode: true

  page-footer:
    left: |
      MScEE Electrical Engineering Project (EEP), M. Meiners, HSB.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
#  cover-image: images/hsb-logo.png
#  favicon: images/hsb-logo.png
  site-url: https://mimeiners.github.io/eeps/
  repo-url: https://github.com/mimeiners/eeps/
  repo-branch: quarto
  repo-actions: [edit, issue]
  downloads: [pdf,epub]

  chapters:
    - index.qmd

    - part: Projects
      chapters:
        - file: docs/mojo.qmd
        - file: docs/osic-tools.qmd
        - file: docs/references.qmd
          
bibliography: _bibliography/references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrbook # scrreptrt
#    lof: true
#    lot: true
    toc: true    
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: ieee
    #    keep-tex: true
    output-file: eeps
  epub:
    theme: flatly
    output-file: eeps
  docx: default

execute:
  freeze: auto

